ADCM-6117: Implement Component object
arenadata/adcm-aio-client pull request #13
Opened 2024-11-20 11:10 UTC by DanBalalan

2024-11-21 06:05 UTC, Sealwing requested changes

2024-11-21 06:05 UTC, Sealwing commented on adcm_aio_client/core/objects/cm.py
> +    PATH_PREFIX = "components"
🐗 

technically it's not prefix 🧌 , it's infix

2024-11-21 07:53 UTC, DanBalalan commented on adcm_aio_client/core/objects/cm.py
> +        return self._parent._parent
refactored

2024-11-21 07:53 UTC, DanBalalan commented on adcm_aio_client/core/objects/cm.py
> +    def hosts(self: Self) -> "HostsInClusterNode":
will be changed in ADCM-6133

2024-11-21 07:53 UTC, DanBalalan commented on pyproject.toml
> +asyncstdlib = "^3.13.0"
`async_cached_property` works with async callables only, so we need both `cached_property` versions

2024-11-21 09:05 UTC, Sealwing submitted a review, later dismissed

2024-11-22 06:28 UTC, Starovoitov submitted a review, later dismissed

2024-11-22 07:43 UTC, Sealwing submitted a review, later dismissed

2024-11-22 07:43 UTC, Starovoitov submitted a review, later dismissed

2024-11-22 07:45 UTC, Sealwing submitted a review, later dismissed

2024-11-22 08:04 UTC, Sealwing approved these changes

2024-11-22 08:07 UTC, Starovoitov approved these changes

2024-11-22 08:53 UTC, merged