[Draft] ADCM-6068: Implement base Accessor
arenadata/adcm-aio-client pull request #2
Opened 2024-11-08 06:36 UTC by Starovoitov

2024-11-11 06:04 UTC, Sealwing requested changes

2024-11-11 06:04 UTC, Sealwing commented on adcm_aio_client/core/accessors.py
> +    async def all(self: Self, page: int = 1, items: int = 10) -> List[T]:
this function doesn't take arguments, it returns everything what's in there

2024-11-11 06:04 UTC, Sealwing commented on adcm_aio_client/core/accessors.py
> +            yield [self._create_object(object) for object in response.as_list()]
same as for the all, also should yield exact objects, not lists of them

I believe all should just `return list(self.iter())`

2024-11-11 06:04 UTC, Sealwing commented on adcm_aio_client/core/accessors.py
> +    async def filter(self: Self, **predicate) -> List[T]:
please see if `list` method really introduces conflict in typing here, maybe we don't have to use List after all

2024-11-13 13:58 UTC, a-alferov approved these changes

2024-11-13 13:58 UTC, Sealwing commented on adcm_aio_client/core/accessors.py
> +    def _gen_page_indexes(
unused, i believe

2024-11-13 13:59 UTC, Sealwing approved these changes

2024-11-14 05:11 UTC, merged