ADCM-6151: Make status an arbitraty string for all objects
arenadata/adcm-aio-client pull request #40
Opened 2024-12-10 09:59 UTC by Starovoitov

2024-12-11 04:38 UTC, Sealwing requested changes

2024-12-11 04:38 UTC, Sealwing commented on adcm_aio_client/core/objects/_common.py
> +        self._data["maintenanceMode"] = maintenance_mode  # pyright: ignore[reportAttributeAccessIssue]
it's not part of data btw

data is raw data from API and shouldn't be changed in that way

2024-12-12 05:02 UTC, Sealwing approved these changes

2024-12-13 04:26 UTC, Sealwing approved these changes

2024-12-13 07:08 UTC, DanBalalan approved these changes

2024-12-13 07:33 UTC, a-alferov approved these changes

2024-12-13 07:39 UTC, merged